### ISSUE TITLE
Feature: delay

### ISSUE THREAD

**Issue by jensdc92** [ncstate-sat/popover#111]
Hi,

It would be great to setup a delay so when hovering above multiple items with a popover not every popover is shown.

Nice work so far!

**Comment by willshowell** [comment]
Hi @jensdc92, I'm afraid delay behavior is a little more domain-specific than we're trying to get with this popover. Since the popover has no "concept" of whether its anchor is hovered or clicked, it also cannot know about hover delays. We expect all the opening and closing behavior to be up to the user.

If you want to see a pretty simple way of adding a delay, check out the "Tooltip" section here:

https://ncstate-sat.github.io/popover/

The source for that component is here:

https://github.com/ncstate-sat/popover/blob/master/src/demo/app/tooltip/tooltip.component.ts

**Comment by jensdc92** [comment]
Thank you, I missed that part in the documentation

**Comment by Abrissirba** [comment]
I created a directive to handle hover and delay. I forked the stackblitz template with the directive and updated the example hover component, https://stackblitz.com/edit/sat-popover-examples-esomkk?file=app%2Fsat-hover.directive.ts.

**Comment by willshowell** [comment]
@Abrissirba thanks for sharing! I didn't want to add that logic directly to the popover, but having a separate directive that handles it is a great idea. I'll open another issue to track publishing this as part of the package.
