### ISSUE TITLE
Being able to hover in the sat-popover while opening it with mouseenter

### ISSUE THREAD

**Issue by Lempkin** [ncstate-sat/popover#143]
If I choose to open the popover by hovering an item, then I'm not able to hover the popover itself (cause the mouseleave event is fired).

I thought that if I set the sat-popover inside the div that throws the mouseenter event it would work, but as it's based on material CDK, this doesn"t work. My code : 

```
<div [satPopoverAnchorFor]="myAppPopover"   (mouseenter)="myAppPopover.open()" >
      <sat-popover #myAppPopover  [autoFocus]="false"  verticalAlign="below"  horizontalAlign="end" >
        <div>
          PopOver content
        </div>
   </sat-popover>
</div>
```

Is there any way to achieve this?

Many thx

**Comment by willshowell** [comment]
An easy way around this (if the ux is suitable for your use case) would be to put the `mouseleave` handler on the popover content. That way it won't close until the user has already interacted with it.

Otherwise you may need to add a bit of extra logic. A couple of options of the top of my head:

- You could add a delay ([see the tooltip demo here](https://ncstate-sat.github.io/popover/)) such that the popover only closes if the mouse doesn't enter the popover within a certain timeframe after leaving the anchor.
- You could track the mouse movements and only close the popover if the cursor moves away from the anchor/popover.

In any case, I think this functionality is beyond the scope of the popover and should exist in user-land. I might be able to be convinced otherwise, but for now I'm going to close this.
