### ISSUE TITLE
Flashing tooltip on hover due to alignment inputs

### ISSUE THREAD

**Issue by Graphictank** [ncstate-sat/popover#171]
A UI requirement for a project I'm working on is asking for a tooltip hover to cover over the original text (mainly due space limitations, most original text gets ellipsis-ed). 

An example: 
![image](https://user-images.githubusercontent.com/8442612/62723120-ead13180-b9dd-11e9-8300-99f0c6ad1785.png)

While a clicked popover (i.e positioning.component) can handle this perfectly, when I set the horizontalAlign and verticalAligns to left justify & horizontally center over hovered tooltip text, it flashes on and off repeatedly. I need to know if there's something I'm missing to have it stay focused until the user moves the mouse away from the targeted div or if this is a bug. 

Any help would be appreciated, the hover code is listed below:  

`        <div
          satPopoverAnchor
          #instantAnchor="satPopoverAnchor"
          class="anchor"
          (mouseenter)="instantPopover.open()"
          (mouseleave)="instantPopover.close()"
        >
        TEST
        </div>`

`
        <sat-popover #instantPopover [anchor]="instantAnchor" horizontalAlign="start" verticalAlign="center">
          <div class="tooltip-wrapper mat-body-1">
            TEST
          </div>
        </sat-popover>`

**Comment by willshowell** [comment]
This sounds like expected (though admittedly frustrating) behavior. The problem is that as soon as the popover displays, the `(mouseleave)` event is triggered on the anchor because the mouse is no longer on that div... it's on the popover.

I would suggest moving the `(mouseleave)` event handler to the popover itself so that

1. hovering the anchor opens the popover
2. as long as the mouse remains within the popover, the popover is visible
3. as soon as the mouse leaves the popover, the popover closes

**Comment by Graphictank** [comment]
> I would suggest moving the `(mouseleave)` event handler to the `.tooltip-wrapper` so that
> 
> 1. hovering the anchor opens the popover
> 2. as long as the mouse remains within the popover, the popover is visible
> 3. as soon as the mouse leaves the popover, the popover closes
> 
 Will! Thanks for your advice, I moved the (mouseleave)="instantPopover.close() in to the tooltip-wrapper class div and it is working well; no flashing in Chrome (and IE11) .

Really appreciate your assistance in troubleshooting this!
